# Generated by Django 3.1.5 on 2021-01-19 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210115_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=144),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 10, 45, 43, 878885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 10, 45, 43, 877888, tzinfo=utc)),
        ),
    ]
