# Generated by Django 3.1.5 on 2021-02-03 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210125_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 7, 52, 16, 562242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 7, 52, 16, 561912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=32),
        ),
    ]
