# Generated by Django 3.1.5 on 2021-01-27 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 0, 1, 45617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdislikes',
            name='dislike_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 0, 1, 46870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 0, 1, 46286, tzinfo=utc)),
        ),
    ]
