# Generated by Django 3.1.5 on 2021-01-27 15:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq_app', '0002_auto_20210127_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 2, 16, 719279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdislikes',
            name='dislike_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 2, 16, 720463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 2, 16, 719892, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 2, 16, 718710, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
