# Generated by Django 3.1.5 on 2021-02-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 10, 38, 23, 155719)),
        ),
    ]
