# Generated by Django 3.1.5 on 2021-01-25 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210118_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 8, 6, 11, 376677, tzinfo=utc), verbose_name='publishing date'),
        ),
    ]
